### ISSUE TITLE
Requests CRUD email integration

### ISSUE THREAD

**Issue by ASbeletsky** [ASbeletsky/time-off-tracker-api#27]
Необходимо реализовать отправку имейлов после создания/редактирования заявки. Для этого:

- Найти почтовый сервис через который можно это сделать
- Реализовать функционал отправки имейлов через Mediator паттерн - в TimeOffRequestService посылать нотификацию о создании/изменении заявки - отлавливать эту нотификацию асинхронно, формировать соответсвующий email и отправлять. Советую использовать https://github.com/jbogard/MediatR

**Comment by PedenkoIllia** [comment]
Письма буду готовить в отдельных ветках, но по этому issue
